const { chromium }=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const config=JSON.parse(fs.readFileSync('tests/fixtures/demo.json','utf8'));
await page.goto('http://localhost:8099/settings.html');
await page.locator('#previewValue').filter({hasText:'自動検出'}).waitFor();
const box=await page.locator('#overlay').boundingBox();
for(const k of ['min','center','max']){
 await page.locator('[data-point="'+k+'"]').click();
 await page.mouse.click(box.x+config[0].points[k][0]*box.width,box.y+config[0].points[k][1]*box.height);
}
await page.locator('#interval_minutes').fill('15');
await page.getByRole('button',{name:'下書きを保存',exact:true}).click();
await page.locator('#status').filter({hasText:'下書きを保存しました'}).waitFor({timeout:3000}).catch(async e=>{console.log(await page.locator('#status').textContent());console.log(await page.locator('#pointList').textContent());console.log(await page.locator('input:invalid').evaluateAll(xs=>xs.map(x=>({id:x.id,message:x.validationMessage,value:x.value}))));throw e;});
let draft=await page.evaluate(()=>JSON.parse(localStorage.getItem('mosa-gauge-draft-v1')));
assert.equal(draft[0].interval_minutes,15);
let downloadPromise=page.waitForEvent('download');
await page.locator('#export').click();const download=await downloadPromise;
assert.equal(download.suggestedFilename(),'gauges.json');
let sent,dispatch;
await page.route('https://api.github.com/repos/MOSA-github/fuel_level_monitoring_system/**',async route=>{
 const req=route.request();
 if(req.method()==='GET')return route.fulfill({json:{sha:'mock-sha',content:Buffer.from(JSON.stringify(config)).toString('base64')}});
 if(req.method()==='PUT'){sent=req.postDataJSON();return route.fulfill({json:{commit:{sha:'mock-result'}}});}
 dispatch=req.postDataJSON();return route.fulfill({status:204});
});
await page.getByText('GitHubへ反映 / 今すぐ解析',{exact:true}).click();
await page.locator('#githubToken').fill('mock-token-for-ui-test');
await page.locator('#publish').click();
await page.locator('#status').filter({hasText:'GitHubへ設定を反映しました'}).waitFor();
assert.equal(sent.sha,'mock-sha');
assert.equal(JSON.parse(Buffer.from(sent.content,'base64'))[0].interval_minutes,15);
assert.ok(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes('mock-token'));
await page.locator('#run').click();
await page.locator('#status').filter({hasText:'解析を依頼しました'}).waitFor();
assert.equal(dispatch.inputs.force,'true');
await page.locator('#publish').click();
await page.locator('#status').filter({hasText:'別の操作で更新'}).waitFor();
await page.locator('#clearToken').click();
assert.equal(await page.locator('#githubToken').inputValue(),'');
await page.goto('http://localhost:8099/settings.html');
await page.locator('#previewValue').filter({hasText:'自動検出'}).waitFor();
fs.mkdirSync('.local',{recursive:true});
await page.screenshot({path:'.local/settings-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'.local/settings-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.goto('http://localhost:8099/settings.html?camera_id=1&facility_id=HOSP-0001');
await page.locator('#facility_id').filter({visible:true}).waitFor();
await page.waitForFunction(()=>document.querySelector('#facility_id').value==='HOSP-0001');
assert.equal(await page.locator('#camera_id').inputValue(),'1');
assert.equal(await page.locator('#enabled').isChecked(),false);
await page.goto('http://localhost:8099/');
await page.getByText('検証用・実測ではありません',{exact:true}).waitFor();
await page.setViewportSize({width:1440,height:1000});
await page.screenshot({path:'.local/dashboard.png',fullPage:true});
const reading={id:'live-1',facility_id:'HOSP-0001',device_id:'water-1',camera_id:'1',type:'water',unit:'%',name:'Camera water',is_demo:false,status:'normal',value:42,updated_at:new Date().toISOString(),interval_minutes:15};
await page.route('https://mosa-github.github.io/fuel_level_monitoring_system/data/latest.json*',r=>r.fulfill({json:{schema_version:1,readings:[reading]}}));
await page.goto('http://localhost:8100/hospital.html?id=HOSP-0001');
await page.getByRole('tab',{name:'貯水・水位',exact:true}).click();
await page.locator('#waterCards').getByText('Camera water',{exact:true}).waitFor();
assert.match(await page.locator('#waterCards').innerText(),/42/);
reading.updated_at='2000-01-01T00:00:00Z';
await page.reload();
await page.getByRole('tab',{name:'貯水・水位',exact:true}).click();
await page.locator('#waterCards').getByText(/期限切れ/).waitFor();
assert.match(await page.locator('#waterCards').innerText(),/データなし/);
assert.deepEqual(errors,[]);
await browser.close();console.log('Browser checks passed: 3-point editing, automatic-needle calibration UI, interval, draft/export, mocked GitHub save/dispatch/conflict, mobile, data integration and stale handling.');
})().catch(e=>{console.error(e);process.exit(1)});
